server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: #执行数据源
    platform: h2 #指定数据源类型
    schema: classpath:schema.sql #指定h2数据库的建表脚本
    data: classpath:data.sql #指定h2数据库的数据脚本
  application:
    name: microservice-provider-user
logging: #配置日志级别，让hibernate打印执行的sql
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

#---
#spring:
#  application:
#    name: abcdef