server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          password: xxxxx
          username: xxxxx
          uri: https://github.com/xym-loveit/springCloud-project.git
          search-paths: config-repo
encrypt:
  key: xym
#logging:
#  level:
#    org.springframework.cloud: debug
#    org.springframework.boot: debug
