server:
  port: 8020
#8010
info:
  app:
    name: '@project.artifactId@'
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@maven.compiler.source@"
      target: "@maven.compiler.target@"
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback-stream
#microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
