server:
  port: 8080
spring:
  rabbitmq:
    username: xym
    virtual-host: /xym
    password: 123456
    host: localhost
    port: 5672
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          password: xxxxx
          username: xxxxxx
          uri: https://github.com/xym-loveit/springCloud-project.git
          search-paths: config-repo
    bus:
      trace:
        enabled: true #跟踪消息总线事件
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug

