server:
  port: 8080
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          password: xxxxx
          username: xxxxx
          uri: https://github.com/xym-loveit/springCloud-project.git
          search-paths: config-repo
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug
#指定eureka注册中心，将config server 服务注册到eureka中，提供给其他config client读取
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
