server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          password: 201025xym##$$
          username: xym_loveit@126.com
          uri: https://github.com/xym-loveit/springCloud-project.git
          search-paths: config-repo
encrypt:
  key-store:
    location: classpath:/server.jks
    password: 123456
    alias: mytestkey
    secret: 123456
#logging:
#  level:
#    org.springframework.cloud: debug
#    org.springframework.boot: debug
